ifeq ($(XILINX_VITIS_AIETOOLS),)
XILINX_VITIS_AIETOOLS:=${XILINX_VITIS}/aietools
endif
VCS_INCLUDES=-I${VCS_HOME}/include/systemc233 -I${VCS_HOME}/include -I${VCS_HOME}/include/cosim/bf 

GPP_SYSC_OPTS=-m64 -O3 -g -DCOMMON_CPP_DLL
export PATH := ${GCC_PATH}/../../binutils-64/bin/:${PATH}
.PHONY: all clean
.NOTPARALLEL:
all: clean link

genwrapper_for_ps_i140: init
	(${GCC_PATH}/g++  -c  $(GPP_SYSC_OPTS) -DVCSSYSTEMC=1  -fPIC -fpermissive -std=c++17 -D__AIE_ARCH__=10 -D__LOCK_FENCE_MODE__=0 -DAIE_OPTION_SCALAR_FLOAT_ON_VECTOR -Wno-deprecated-declarations -Werror=return-type -DSC_INCLUDE_DYNAMIC_PROCESSES -D__AIESIM__ -D__PS_INIT_AIE__ -DXAIE_DEBUG -D main\(...\)=ps_main\(...\) -O3 -flto $(VCS_INCLUDES) -I$(XILINX_VITIS_AIETOOLS)/include -I$(XILINX_VITIS_AIETOOLS)/include/drivers/aiengine -I${XILINX_HLS}/include -I$(XILINX_VITIS_AIETOOLS)/tps/boost_1_72_0 -I. -I$(XILINX_VITIS_AIETOOLS)/include/xtlm/include -I$(XILINX_VITIS_AIETOOLS)/include/common_cpp/common_cpp_v1_0/include -I "../../../.."  -I "/usr/xilinx/Vitis/2023.2/aietools/include"  -I "/home/luanxinya/SVD/FPGA_test/128/./aie"  -I "/home/luanxinya/SVD/FPGA_test/128/./"  -o vcs.dir/generated-objects/genwrapper_for_ps_i140.o generated-source/genwrapper_for_ps_i140.cpp)

link: genwrapper_for_ps_i140
	( ${GCC_PATH}/g++ -m64  -o vcs.dir/generated-objects/aie_crts_ps.so vcs.dir/generated-objects/genwrapper_for_ps_i140.o -shared -Wl,--as-needed -lxaiengine -lxioutils -ladf_api -flto -L $(XILINX_VITIS_AIETOOLS)/lib/lnx64.o)

init:
ifneq ($(wildcard ~/vcs.dir/*),)
	@echo ""
else
	mkdir -p vcs.dir/generated-objects
endif

clean:
	(rm -rf vcs.dir)
