ifeq ($(XILINX_VITIS_AIETOOLS),)
XILINX_VITIS_AIETOOLS:=${XILINX_VITIS}/aietools
endif
RIVIERA_GCC_HOME=${RIVIERA_HOME}/gcc_Linux64/
RIVIERA_INCLUDES=-I${RIVIERA_HOME}/../systemc/interface

.PHONY: all clean
.NOTPARALLEL:
all: clean link

genwrapper_for_ps_i140: init
	(${RIVIERA_HOME}/bin/ccomp  -c -m64 -sc  -fPIC -fpermissive -std=c++17 -D__AIE_ARCH__=10 -D__LOCK_FENCE_MODE__=0 -DAIE_OPTION_SCALAR_FLOAT_ON_VECTOR -Wno-deprecated-declarations -Werror=return-type -DSC_INCLUDE_DYNAMIC_PROCESSES -D__AIESIM__ -D__PS_INIT_AIE__ -DXAIE_DEBUG -O3 -flto -D main\\\(...\\\)=ps_main\\\(...\\\) $(RIVIERA_INCLUDES) -I$(XILINX_VITIS_AIETOOLS)/include -I$(XILINX_VITIS_AIETOOLS)/include/drivers/aiengine -I${XILINX_HLS}/include -I$(XILINX_VITIS_AIETOOLS)/tps/boost_1_72_0 -I. -I$(XILINX_VITIS_AIETOOLS)/include/xtlm/include -I$(XILINX_VITIS_AIETOOLS)/include/common_cpp/common_cpp_v1_0/include -I "../../../.."  -I "/usr/xilinx/Vitis/2023.2/aietools/include"  -I "/home/luanxinya/SVD/FPGA_test/128/./aie"  -I "/home/luanxinya/SVD/FPGA_test/128/./"  -o riviera.dir/generated-objects/genwrapper_for_ps_i140.o generated-source/genwrapper_for_ps_i140.cpp)

link: genwrapper_for_ps_i140
	(${RIVIERA_HOME}/bin/ccomp  -shared -Wl,--as-needed -lxaiengine -lxioutils -ladf_api -flto -L $(XILINX_VITIS_AIETOOLS)/lib/lnx64.o  --no-debug   -o riviera.dir/generated-objects/aie_crts_ps.so riviera.dir/generated-objects/genwrapper_for_ps_i140.o)

init:
ifneq ($(wildcard ~/riviera.dir/*),)
	@echo ""
else
	mkdir -p riviera.dir/generated-objects
endif

clean:
	(rm -rf riviera.dir)
