// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module TopPL_dataflow_parent_loop_proc (
        send_fifo_0_dout,
        send_fifo_0_empty_n,
        send_fifo_0_read,
        sweep_tx0_0_TDATA,
        sweep_tx0_0_TKEEP,
        sweep_tx0_0_TSTRB,
        sweep_tx0_0_TLAST,
        send_fifo_1_dout,
        send_fifo_1_empty_n,
        send_fifo_1_read,
        sweep_tx0_1_TDATA,
        sweep_tx0_1_TKEEP,
        sweep_tx0_1_TSTRB,
        sweep_tx0_1_TLAST,
        ap_clk,
        ap_rst,
        sweep_tx0_0_TVALID,
        sweep_tx0_0_TREADY,
        sweep_tx0_1_TVALID,
        sweep_tx0_1_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [127:0] send_fifo_0_dout;
input   send_fifo_0_empty_n;
output   send_fifo_0_read;
output  [127:0] sweep_tx0_0_TDATA;
output  [15:0] sweep_tx0_0_TKEEP;
output  [15:0] sweep_tx0_0_TSTRB;
output  [0:0] sweep_tx0_0_TLAST;
input  [127:0] send_fifo_1_dout;
input   send_fifo_1_empty_n;
output   send_fifo_1_read;
output  [127:0] sweep_tx0_1_TDATA;
output  [15:0] sweep_tx0_1_TKEEP;
output  [15:0] sweep_tx0_1_TSTRB;
output  [0:0] sweep_tx0_1_TLAST;
input   ap_clk;
input   ap_rst;
output   sweep_tx0_0_TVALID;
input   sweep_tx0_0_TREADY;
output   sweep_tx0_1_TVALID;
input   sweep_tx0_1_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_send_fifo_0_read;
wire   [127:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TDATA;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TKEEP;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TSTRB;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TLAST;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_send_fifo_1_read;
wire   [127:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TDATA;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TKEEP;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TSTRB;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TLAST;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TVALID;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TVALID;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_idle;
reg    dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_continue;
reg   [6:0] loop_dataflow_input_count;
reg   [6:0] loop_dataflow_output_count;
wire   [6:0] bound_minus_1;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 7'd0;
#0 loop_dataflow_output_count = 7'd0;
end

TopPL_dataflow_in_loop_VITIS_LOOP_172_2 dataflow_in_loop_VITIS_LOOP_172_2_U0(
    .send_fifo_0_dout(send_fifo_0_dout),
    .send_fifo_0_empty_n(send_fifo_0_empty_n),
    .send_fifo_0_read(dataflow_in_loop_VITIS_LOOP_172_2_U0_send_fifo_0_read),
    .sweep_tx0_0_TDATA(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TDATA),
    .sweep_tx0_0_TKEEP(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TKEEP),
    .sweep_tx0_0_TSTRB(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TSTRB),
    .sweep_tx0_0_TLAST(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TLAST),
    .send_fifo_1_dout(send_fifo_1_dout),
    .send_fifo_1_empty_n(send_fifo_1_empty_n),
    .send_fifo_1_read(dataflow_in_loop_VITIS_LOOP_172_2_U0_send_fifo_1_read),
    .sweep_tx0_1_TDATA(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TDATA),
    .sweep_tx0_1_TKEEP(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TKEEP),
    .sweep_tx0_1_TSTRB(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TSTRB),
    .sweep_tx0_1_TLAST(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TLAST),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .sweep_tx0_0_TVALID(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TVALID),
    .sweep_tx0_0_TREADY(sweep_tx0_0_TREADY),
    .ap_start(dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_start),
    .ap_done(dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_done),
    .sweep_tx0_1_TVALID(dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TVALID),
    .sweep_tx0_1_TREADY(sweep_tx0_1_TREADY),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_ready),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_idle),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 7'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 7'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 7'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 7'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 7'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 7'd0) & (ap_start == 1'b0) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_continue = 1'b0;
    end
end

assign bound_minus_1 = (7'd120 - 7'd1);

assign dataflow_in_loop_VITIS_LOOP_172_2_U0_ap_start = ap_start;

assign send_fifo_0_read = dataflow_in_loop_VITIS_LOOP_172_2_U0_send_fifo_0_read;

assign send_fifo_1_read = dataflow_in_loop_VITIS_LOOP_172_2_U0_send_fifo_1_read;

assign sweep_tx0_0_TDATA = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TDATA;

assign sweep_tx0_0_TKEEP = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TKEEP;

assign sweep_tx0_0_TLAST = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TLAST;

assign sweep_tx0_0_TSTRB = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TSTRB;

assign sweep_tx0_0_TVALID = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_0_TVALID;

assign sweep_tx0_1_TDATA = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TDATA;

assign sweep_tx0_1_TKEEP = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TKEEP;

assign sweep_tx0_1_TLAST = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TLAST;

assign sweep_tx0_1_TSTRB = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TSTRB;

assign sweep_tx0_1_TVALID = dataflow_in_loop_VITIS_LOOP_172_2_U0_sweep_tx0_1_TVALID;

endmodule //TopPL_dataflow_parent_loop_proc
