-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

Library ieee;
use ieee.std_logic_1164.all;

entity TopPL_printdouble is 
    port (
        ap_clk      : in std_logic;
        ap_rst      : in std_logic;
        ap_ce       : in std_logic;
        fmt         : in std_logic_vector(31 downto 0);
        v           : in std_logic_vector(63 downto 0)
    );
end entity;
architecture arch of TopPL_printdouble is 
-- This avoids an error during impl
signal dummy: std_logic_vector(31 downto 0);
begin
    dummy <= fmt;
end architecture;

